#!/bin/bash
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
panel="$here/../Panel.qml"
service="$here/../Service.qml"
plain_text="$here/../PlainText.qml"
sparkline="$here/../Sparkline.qml"
subscription_prompt="$here/../SubscriptionPrompt.qml"
routing_prompt="$here/../RoutingPresetPrompt.qml"
onboarding_wizard="$here/../OnboardingWizard.qml"
startup_prompt="$here/../StartupPrompt.qml"
routing_tools_prompt="$here/../RoutingToolsPrompt.qml"
import_preview_prompt="$here/../ImportPreviewPrompt.qml"
installer="$here/../install.sh"
uninstaller="$here/../uninstall.sh"

grep -q 'moduleName: "kdk.omavless"' "$panel"
grep -q 'ipcTarget: "kdk.omavless"' "$panel"
grep -q 'title: "OmaVLESS"' "$panel"
! grep -q 'title: "Omavless"' "$panel"
grep -q 'barDisconnectedIcon: "󰒙"' "$panel"
grep -q 'barConnectedIcon: "󰒘"' "$panel"
grep -q 'heroDisconnectedIcon: "󰴴"' "$panel"
grep -q 'heroConnectedIcon: "󰴳"' "$panel"
grep -q 'problemIcon: ""' "$panel"
! grep -q 'problemIcon: "󰻍"' "$panel"
grep -q 'root.barStatusIcon + " " + vless.barThroughput' "$panel"
grep -q 'function safeTooltip(value, maximum)' "$panel"
grep -q 'tooltipText: root.safeTooltip(root.barTooltip, 220)' "$panel"
grep -Fq 'return text.replace(/&/g, "＆").replace(/</g, "‹").replace(/>/g, "›")' "$service"
! grep -q 'tooltipText: root.barTooltip' "$panel"
! grep -q 'tooltipText: "Show " + vless.primaryName' "$panel"
! grep -q 'text: groupTitle.text + "\\n" + groupSummary.text' "$panel"
! grep -q 'text: subscriptionTitle.text + "\\n" + subscriptionSummary.text' "$panel"
! grep -q 'tooltipText: (serverRow.profile' "$panel"
! grep -q 'tooltipText: (configRow.profile' "$panel"
! grep -q 'tooltipText: "Edit config or name for " +' "$panel"
! grep -q 'tooltipText: "Show " + (configRow.profile' "$panel"
! grep -q 'tooltipText: "Delete " + (configRow.profile' "$panel"
grep -q 'message: root.safeTooltip("Delete profile "' "$panel"
grep -q 'message: root.safeTooltip("Remove subscription "' "$panel"
! grep -q 'message: "Delete profile " +' "$panel"
! grep -q 'message: "Remove subscription "' "$panel"
grep -q 'function safeTooltip(value)' "$startup_prompt"
grep -q 'text: prompt.safeTooltip(modelData.name)' "$startup_prompt"
grep -q 'tooltipText: prompt.safeTooltip(modelData.name)' "$startup_prompt"
! grep -q 'tooltipText: modelData.name' "$startup_prompt"
grep -q 'Style.space(600)' "$panel"
grep -q 'id: uptimeText' "$panel"
! grep -q 'detail: vless.active' "$panel"
grep -q 'trafficRxColor: "#55d6be"' "$panel"
grep -q 'trafficTxColor: "#c792ea"' "$panel"
grep -q 'ctx.setLineDash(dashed ? \[5, 4\] : \[\])' "$sparkline"
grep -q 'text: root.heroStatusIcon' "$panel"
! grep -q 'text: "󰖂"' "$panel"
grep -q 'function looksLikeConfig' "$service"
grep -q 'JSON.parse(String(raw || ""))' "$service"
grep -q 'typeof payload.transport !== "string"' "$service"
grep -q 'property var routing:' "$service"
grep -q 'property var coreSetup:' "$service"
grep -q 'property var startup:' "$service"
grep -q 'property bool onboardingComplete:' "$service"
grep -q 'function configureStartup(enabled, target, profileUuid, mode)' "$service"
grep -q 'function completeOnboarding()' "$service"
grep -q 'function loadCustomRules()' "$service"
grep -q 'function addCustomRule(kind, action, value)' "$service"
grep -q 'function checkRoute(value)' "$service"
grep -q 'function refreshRuleProviders()' "$service"
grep -q 'function toggleFavorite(profile)' "$service"
grep -q 'function previewImport(kind, payload, suggestedName)' "$service"
grep -q 'function exportDiagnostics()' "$service"
grep -Eq '^[[:space:]]*property var capabilities:' "$service"
! grep -q 'readonly property var capabilities:' "$service"
grep -q 'capabilities = featureMap' "$service"
grep -q 'function supports(name)' "$service"
grep -q 'property var conflicts:' "$service"
grep -q 'property string exitIp:' "$service"
grep -q 'property var rxHistory:' "$service"
grep -q 'function plainText(value, maximum)' "$service"
grep -q 'textFormat: Text.PlainText' "$plain_text"
for qml in "$panel" "$service" "$subscription_prompt" "$routing_prompt" \
  "$onboarding_wizard" "$startup_prompt" "$routing_tools_prompt" \
  "$import_preview_prompt" \
  "$here/../NamePrompt.qml" \
  "$here/../RenameWindow.qml" "$here/../QrWindow.qml"; do
  ! grep -Eq '(^|[^A-Za-z])Text \{' "$qml"
done
grep -q 'function drawSeries' "$sparkline"
grep -q 'id: profileSearch' "$panel"
grep -q 'function profileMatches' "$panel"
grep -q 'Exit IP is this request' "$panel"
grep -q 'Possible full-tunnel conflict' "$panel"
grep -q 'routing.source === "roscomvpn"' "$service"
grep -q 'text: vless.active ? "ACTIVE ROUTING" : "ROUTING ON CONNECT"' "$panel"
grep -q 'text: vless.routingSummary' "$panel"
grep -q '{ label: "Routing", mode: "rule" }' "$panel"
grep -q '{ label: "Full VPN", mode: "global" }' "$panel"
grep -q '{ label: "Direct", mode: "direct" }' "$panel"
full_line="$(grep -n '{ label: "Full VPN", mode: "global" }' "$panel" | head -n 1 | cut -d: -f1)"
routing_line="$(grep -n '{ label: "Routing", mode: "rule" }' "$panel" | head -n 1 | cut -d: -f1)"
direct_line="$(grep -n '{ label: "Direct", mode: "direct" }' "$panel" | head -n 1 | cut -d: -f1)"
(( full_line < routing_line && routing_line < direct_line ))
grep -q 'root.requestRoutingMode(parent.modelData.mode)' "$panel"
grep -q 'function useRoutingPreset(profile, keepMode)' "$service"
grep -q 'RoutingPresetPrompt {' "$panel"
grep -q 'OnboardingWizard {' "$panel"
grep -q 'StartupPrompt {' "$panel"
grep -q 'RoutingToolsPrompt {' "$panel"
grep -q 'ImportPreviewPrompt {' "$panel"
grep -q 'text: "SET UP OMAVLESS"' "$onboarding_wizard"
grep -q 'text: "START AT LOGIN"' "$startup_prompt"
grep -q 'leftText: "Full VPN"' "$startup_prompt"
grep -q 'rightText: "Routing"' "$startup_prompt"
! grep -q 'Direct' "$startup_prompt"
grep -q 'text: "ROUTING TOOLS"' "$routing_tools_prompt"
grep -q 'text: "Where will this destination go?"' "$routing_tools_prompt"
grep -q 'text: "Custom rules"' "$routing_tools_prompt"
grep -q 'text: "Refresh now"' "$routing_tools_prompt"
grep -q 'no page is loaded' "$routing_tools_prompt"
grep -q 'text: "Review before import"' "$import_preview_prompt"
grep -q 'complete access credential and key parameters are intentionally not shown' "$import_preview_prompt"
grep -q 'credentialHint' "$import_preview_prompt"
grep -q '{ label: "Protocol", value: String(prompt.preview.protocol' "$import_preview_prompt"
grep -q 'compatibilityNote' "$import_preview_prompt"
grep -q 'advancedXhttp' "$import_preview_prompt"
grep -q 'prompt.preview.experimental' "$import_preview_prompt"
grep -q 'onClicked: wizard.copyCommand(commandRow.command)' "$onboarding_wizard"
! grep -q 'runControl' "$onboarding_wizard"
grep -q 'text: "Choose Routing preset"' "$routing_prompt"
grep -q 'Keys.onReturnPressed: if (accepted) confirmed(selectedPreset)' "$routing_prompt"
grep -q 'omarchy bar set ' "$panel"
grep -q 'text: "SETTINGS"' "$panel"
grep -q 'else if (t === "g" || t === "G") root.openSettings()' "$panel"
grep -q 'function setRoutingMode(mode)' "$service"
grep -q 'runControl(\["set-mode", value\])' "$service"
grep -q 'function diagnostics(): string' "$panel"
diagnostics_block="$(sed -n '/function diagnostics(): string {/,/function details(): string/p' "$panel")"
! grep -q 'lastError\|profileId\|subscriptionUrl' <<<"$diagnostics_block"
grep -q 'title: "Safe diagnostics"' "$panel"
grep -q 'No profile credentials, keys, server names or subscription URLs' "$panel"
grep -q 'function subscriptions()' "$panel"
grep -q 'root.openSubscriptions()' "$panel"
grep -q 'Qt.callLater(root.openSubscriptions)' "$panel"
! grep -q 'function findByIfname' "$service"
! grep -q 'confIfname' "$service"
! grep -q 'findByIfname\|countByIfname\|confIfname' "$panel"
grep -q '(vless|trojan|hysteria2|hy2|tuic):\\/\\/' "$service"
grep -q '"xhttp", "quic"' "$service"
grep -q 'root.capabilities.protocols.indexOf(value.protocol)' "$service"
grep -q 'hysteria2Experimental' "$service"
grep -q 'tuicExperimental' "$service"
grep -Fq '!/^••••(?:[0-9a-f]{4})?$/i.test(value.credentialHint)' "$service"
grep -q 'runControl(\["import", "--"' "$service"
grep -q 'root.previewImport("text", text, root.suggestName())' "$service"
grep -q 'previewProcess.stdinEnabled = sourceKind === "text"' "$service"
grep -q 'diagnostics-export' "$service"
grep -q 'runControl(\["subscription-save", "--"' "$service"
grep -q 'runControl(\["rename", profile.uuid, "--", value\])' "$service"
grep -q '"edit", _editUuid, "--", _editName' "$service"
grep -q '"notify-drop", drop.uuid\]' "$service"
! grep -q '"notify-drop", drop.uuid, drop.name' "$service"
grep -q 'function probeSubscription(subscription)' "$service"
grep -q 'function cancelProbe()' "$service"
grep -q 'property int probeElapsedSeconds: 0' "$service"
grep -q 'property var subscriptionProbeTimes' "$service"
grep -q 'readonly property int managedProfileCount' "$service"
grep -q '"subscription-probe-stream"' "$service"
grep -q 'stdout: SplitParser' "$service"
grep -q 'function applyProbeEvent(raw, expectedSubscriptionUuid)' "$service"
grep -q 'function testActiveConnection()' "$service"
grep -q 'text: "Test"' "$panel"
grep -q 'onClicked: vless.testActiveConnection()' "$panel"
grep -q 'component SubscriptionGroupRow' "$panel"
grep -q 'component SubscriptionServerRow' "$panel"
grep -q 'root.toggleSubscriptionGroup' "$panel"
grep -q 'root.probeLabel' "$panel"
grep -q 'property var subscriptionSortModes' "$panel"
grep -q 'function cycleSubscriptionPingSort' "$panel"
grep -q 'component SubscriptionSortRow' "$panel"
grep -q 'text: sortRow.sortMode === "pingAsc" ? "Ping ↑"' "$panel"
grep -q '"Failed checks stay last"' "$panel"
grep -q '"managed profile", "managed profiles"' "$panel"
grep -q 'component SubscriptionStatusRow' "$panel"
grep -q 'root.page === "settings" ? settingsColumn.implicitHeight : column.implicitHeight' "$panel"
grep -q 'function probeAge(subscriptionUuid)' "$panel"
grep -q 'function toggleSubscriptionProbe(subscription)' "$panel"
grep -q 'text: testing ? "Cancel" : "Test"' "$panel"
grep -q 'root.toggleSubscriptionProbe(groupRow.subscription)' "$panel"
grep -q '"Run an end-to-end proxy check through every server (p)"' "$panel"
grep -q 'readonly property real scrollGutter: Style.space(16)' "$panel"
grep -q 'if (!pointerSelectingConfig) scrollCursorIntoView()' "$panel"
grep -q 'component SubscriptionServerRow: CursorSurface' "$panel"
grep -q 'vless.toggleFavorite' "$panel"
grep -q 'profile.favorite' "$panel"
grep -q 'bordered: true' "$panel"
grep -q '_dropWarningText' "$service"
grep -q '&& !root.active' "$service"
grep -q 'text: "Subscriptions…"' "$panel"
! grep -q 'onHoveredChanged: if (hovered)' "$panel"
grep -q 'URL stays private' "$panel"
grep -q 'echoMode: reveal.checked' "$subscription_prompt"
grep -q 'property bool error: false' "$subscription_prompt"
grep -q 'Subscription URLs may contain access credentials' "$subscription_prompt"
grep -q 'controlProcess.stdinEnabled = true' "$service"
grep -q 'URI contains the access credential' "$service"
grep -q 'head -c 65537' "$service"
grep -q 'Clipboard content is too large to import' "$service"
grep -q 'statusPollIntervalMs' "$service"
grep -q 'statusFailureCount = Math.min' "$service"
grep -q '/sys/class/net/\$d/statistics' "$service"
grep -q 'rx - prev.rx' "$service"
grep -q 'tx - prev.tx' "$service"
! grep -q '/traffic' "$service"
! grep -q 'vless-last' "$service"
grep -q 'moduleName: "kdk.omavless"' "$panel"
grep -q 'fresh_install=false' "$installer"
grep -q 'local-plugin watcher debounces' "$installer"
grep -q '"$plugin_dir/uninstall.sh"' "$installer"
grep -q '"$plugin_dir/SubscriptionPrompt.qml"' "$installer"
grep -q '"$plugin_dir/RoutingPresetPrompt.qml"' "$installer"
grep -q '"$plugin_dir/OnboardingWizard.qml"' "$installer"
grep -q '"$plugin_dir/StartupPrompt.qml"' "$installer"
grep -q '"$plugin_dir/RoutingToolsPrompt.qml"' "$installer"
grep -q '"$plugin_dir/ImportPreviewPrompt.qml"' "$installer"
grep -q '"$plugin_dir/PlainText.qml"' "$installer"
grep -q '"$plugin_dir/Sparkline.qml"' "$installer"
grep -q '"$plugin_dir/CHANGELOG.md"' "$installer"
! grep -q 'omarchy plugin disable' "$installer"
! grep -q 'omarchy restart shell' "$installer"
bash -n "$installer"
bash -n "$uninstaller"

if command -v qmllint >/dev/null 2>&1; then
  qmllint "$panel"
  qmllint "$service"
  qmllint "$subscription_prompt"
  qmllint "$routing_prompt"
  qmllint "$onboarding_wizard"
  qmllint "$startup_prompt"
  qmllint "$routing_tools_prompt"
  qmllint "$import_preview_prompt"
  qmllint "$plain_text"
  qmllint "$sparkline"
fi

echo "QML contracts: ok"
