#!/bin/bash
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
panel="$here/../Panel.qml"
service="$here/../Service.qml"
plain_text="$here/../PlainText.qml"
sparkline="$here/../Sparkline.qml"
subscription_prompt="$here/../SubscriptionPrompt.qml"
installer="$here/../install.sh"
uninstaller="$here/../uninstall.sh"

grep -q 'moduleName: "kdk.omavless"' "$panel"
grep -q 'ipcTarget: "kdk.omavless"' "$panel"
grep -q 'title: "OmaVLESS"' "$panel"
! grep -q 'title: "Omavless"' "$panel"
grep -q 'barDisconnectedIcon: "󰒙"' "$panel"
grep -q 'barConnectedIcon: "󰒘"' "$panel"
grep -q 'heroDisconnectedIcon: "󰴴"' "$panel"
grep -q 'heroConnectedIcon: "󰴳"' "$panel"
grep -q 'problemIcon: ""' "$panel"
! grep -q 'problemIcon: "󰻍"' "$panel"
grep -q 'root.barStatusIcon + " " + vless.barThroughput' "$panel"
grep -q 'tooltipText: root.barTooltip' "$panel"
grep -q 'Style.space(600)' "$panel"
grep -q 'id: uptimeText' "$panel"
! grep -q 'detail: vless.active' "$panel"
grep -q 'trafficRxColor: "#55d6be"' "$panel"
grep -q 'trafficTxColor: "#c792ea"' "$panel"
grep -q 'ctx.setLineDash(dashed ? \[5, 4\] : \[\])' "$sparkline"
grep -q 'text: root.heroStatusIcon' "$panel"
! grep -q 'text: "󰖂"' "$panel"
grep -q 'function looksLikeConfig' "$service"
grep -q 'JSON.parse(String(raw || ""))' "$service"
grep -q 'typeof payload.transport !== "string"' "$service"
grep -q 'property var routing:' "$service"
grep -Eq '^[[:space:]]*property var capabilities:' "$service"
! grep -q 'readonly property var capabilities:' "$service"
grep -q 'capabilities = featureMap' "$service"
grep -q 'function supports(name)' "$service"
grep -q 'property var conflicts:' "$service"
grep -q 'property string exitIp:' "$service"
grep -q 'property var rxHistory:' "$service"
grep -q 'function plainText(value, maximum)' "$service"
grep -q 'textFormat: Text.PlainText' "$plain_text"
for qml in "$panel" "$service" "$subscription_prompt" \
  "$here/../NamePrompt.qml" "$here/../RenameWindow.qml" "$here/../QrWindow.qml"; do
  ! grep -Eq '(^|[^A-Za-z])Text \{' "$qml"
done
grep -q 'function drawSeries' "$sparkline"
grep -q 'id: profileSearch' "$panel"
grep -q 'function profileMatches' "$panel"
grep -q 'Exit IP is this request' "$panel"
grep -q 'Possible full-tunnel conflict' "$panel"
grep -q 'routing.source === "roscomvpn"' "$service"
grep -q 'text: vless.active ? "ACTIVE ROUTING" : "ROUTING ON CONNECT"' "$panel"
grep -q 'text: vless.routingSummary' "$panel"
grep -q '{ label: "Routing", mode: "rule" }' "$panel"
grep -q '{ label: "Full VPN", mode: "global" }' "$panel"
grep -q '{ label: "Direct", mode: "direct" }' "$panel"
grep -q 'vless.setRoutingMode(parent.modelData.mode)' "$panel"
grep -q 'function setRoutingMode(mode)' "$service"
grep -q 'runControl(\["set-mode", value\])' "$service"
grep -q 'function diagnostics(): string' "$panel"
grep -q 'function subscriptions()' "$panel"
grep -q 'root.openSubscriptions()' "$panel"
grep -q 'Qt.callLater(root.openSubscriptions)' "$panel"
! grep -q 'function findByIfname' "$service"
! grep -q 'confIfname' "$service"
! grep -q 'findByIfname\|countByIfname\|confIfname' "$panel"
grep -q 'vless:\\/\\/' "$service"
grep -q 'runControl(\["import"' "$service"
grep -q 'runControl(\["subscription-save"' "$service"
grep -q 'function probeSubscription(subscription)' "$service"
grep -q 'function cancelProbe()' "$service"
grep -q 'property int probeElapsedSeconds: 0' "$service"
grep -q 'property var subscriptionProbeTimes' "$service"
grep -q 'readonly property int managedProfileCount' "$service"
grep -q '"subscription-probe-stream"' "$service"
grep -q 'stdout: SplitParser' "$service"
grep -q 'function applyProbeEvent(raw, expectedSubscriptionUuid)' "$service"
grep -q 'function testActiveConnection()' "$service"
grep -q 'text: "Test"' "$panel"
grep -q 'onClicked: vless.testActiveConnection()' "$panel"
grep -q 'component SubscriptionGroupRow' "$panel"
grep -q 'component SubscriptionServerRow' "$panel"
grep -q 'root.toggleSubscriptionGroup' "$panel"
grep -q 'root.probeLabel' "$panel"
grep -q 'property var subscriptionSortModes' "$panel"
grep -q 'function cycleSubscriptionPingSort' "$panel"
grep -q 'component SubscriptionSortRow' "$panel"
grep -q 'text: sortRow.sortMode === "pingAsc" ? "Ping ↑"' "$panel"
grep -q '"Failed checks stay last"' "$panel"
grep -q '"managed profile", "managed profiles"' "$panel"
grep -q 'component SubscriptionStatusRow' "$panel"
grep -q 'root.page === "subscriptions" ? subscriptionsColumn.implicitHeight : column.implicitHeight' "$panel"
grep -q 'function probeAge(subscriptionUuid)' "$panel"
grep -q 'function toggleSubscriptionProbe(subscription)' "$panel"
grep -q 'text: testing ? "Cancel" : "Test"' "$panel"
grep -q 'root.toggleSubscriptionProbe(groupRow.subscription)' "$panel"
grep -q '"Run an end-to-end VLESS check through every server (p)"' "$panel"
grep -q 'readonly property real scrollGutter: Style.space(16)' "$panel"
grep -q 'if (!pointerSelectingConfig) scrollCursorIntoView()' "$panel"
grep -q 'component SubscriptionServerRow: CursorSurface' "$panel"
grep -q 'bordered: true' "$panel"
grep -q '_dropWarningText' "$service"
grep -q '&& !root.active' "$service"
grep -q 'text: "Subscriptions…"' "$panel"
! grep -q 'onHoveredChanged: if (hovered)' "$panel"
grep -q 'URL stays private' "$panel"
grep -q 'echoMode: reveal.checked' "$subscription_prompt"
grep -q 'property bool error: false' "$subscription_prompt"
grep -q 'Subscription URLs may contain access credentials' "$subscription_prompt"
grep -q 'controlProcess.stdinEnabled = true' "$service"
grep -q 'URI contains the access credential' "$service"
grep -q 'head -c 65537' "$service"
grep -q 'Clipboard content is too large to import' "$service"
grep -q 'statusPollIntervalMs' "$service"
grep -q 'statusFailureCount = Math.min' "$service"
grep -q '/sys/class/net/\$d/statistics' "$service"
grep -q 'rx - prev.rx' "$service"
grep -q 'tx - prev.tx' "$service"
! grep -q '/traffic' "$service"
! grep -q 'vless-last' "$service"
! grep -q 'moduleName: "glafeara.wireguard"' "$panel"
grep -q 'fresh_install=false' "$installer"
grep -q 'local-plugin watcher debounces' "$installer"
grep -q '"$plugin_dir/uninstall.sh"' "$installer"
grep -q '"$plugin_dir/SubscriptionPrompt.qml"' "$installer"
grep -q '"$plugin_dir/PlainText.qml"' "$installer"
grep -q '"$plugin_dir/Sparkline.qml"' "$installer"
grep -q '"$plugin_dir/CHANGELOG.md"' "$installer"
! grep -q 'omarchy plugin disable' "$installer"
! grep -q 'omarchy restart shell' "$installer"
bash -n "$installer"
bash -n "$uninstaller"

if command -v qmllint >/dev/null 2>&1; then
  qmllint "$panel"
  qmllint "$service"
  qmllint "$subscription_prompt"
  qmllint "$plain_text"
  qmllint "$sparkline"
fi

echo "QML contracts: ok"
