#!/bin/bash
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
panel="$here/../Panel.qml"
service="$here/../Service.qml"
advanced_diagnostics="$here/../AdvancedDiagnostics.qml"
plain_text="$here/../PlainText.qml"
sparkline="$here/../Sparkline.qml"
subscription_prompt="$here/../SubscriptionPrompt.qml"
routing_prompt="$here/../RoutingPresetPrompt.qml"
onboarding_wizard="$here/../OnboardingWizard.qml"
startup_prompt="$here/../StartupPrompt.qml"
routing_tools_prompt="$here/../RoutingToolsPrompt.qml"
import_preview_prompt="$here/../ImportPreviewPrompt.qml"
i18n="$here/../I18n.js"
installer="$here/../install.sh"
uninstaller="$here/../uninstall.sh"

grep -q 'moduleName: "kdk.omavless"' "$panel"
grep -q 'ipcTarget: "kdk.omavless"' "$panel"
grep -q 'title: "OmaVLESS"' "$panel"
! grep -q 'title: "Omavless"' "$panel"
grep -q 'barDisconnectedIcon: "󰒙"' "$panel"
grep -q 'barConnectedIcon: "󰒘"' "$panel"
grep -q 'heroDisconnectedIcon: "󰴴"' "$panel"
grep -q 'heroConnectedIcon: "󰴳"' "$panel"
grep -q 'problemIcon: ""' "$panel"
! grep -q 'problemIcon: "󰻍"' "$panel"
grep -q 'root.barStatusIcon + " " + vless.barThroughput' "$panel"
grep -q 'function safeTooltip(value, maximum)' "$panel"
grep -q 'tooltipText: root.safeTooltip(root.barTooltip, 220)' "$panel"
grep -q 'root.safeTooltip(root.textFor("status.connected_named"' "$panel"
grep -Fq 'return text.replace(/&/g, "＆").replace(/</g, "‹").replace(/>/g, "›")' "$service"
! grep -q 'tooltipText: root.barTooltip' "$panel"
! grep -q 'tooltipText: "Show " + vless.primaryName' "$panel"
! grep -q 'meta: vless.active ? "Connected: " + vless.activeNames.join' "$panel"
! grep -q 'text: groupTitle.text + "\\n" + groupSummary.text' "$panel"
! grep -q 'text: subscriptionTitle.text + "\\n" + subscriptionSummary.text' "$panel"
! grep -q 'tooltipText: (serverRow.profile' "$panel"
! grep -q 'tooltipText: (configRow.profile' "$panel"
! grep -q 'tooltipText: "Edit config or name for " +' "$panel"
! grep -q 'tooltipText: "Show " + (configRow.profile' "$panel"
! grep -q 'tooltipText: "Delete " + (configRow.profile' "$panel"
grep -q 'message: root.safeTooltip("Delete profile "' "$panel"
grep -q 'message: root.safeTooltip("Remove subscription "' "$panel"
! grep -q 'message: "Delete profile " +' "$panel"
! grep -q 'message: "Remove subscription "' "$panel"
grep -q 'function safeTooltip(value)' "$startup_prompt"
grep -q 'text: prompt.safeTooltip(modelData.name)' "$startup_prompt"
grep -q 'tooltipText: prompt.safeTooltip(modelData.name)' "$startup_prompt"
! grep -q 'tooltipText: modelData.name' "$startup_prompt"
grep -q 'Style.space(600)' "$panel"
grep -q 'id: uptimeText' "$panel"
! grep -q 'detail: vless.active' "$panel"
grep -q 'trafficRxColor: "#55d6be"' "$panel"
grep -q 'trafficTxColor: "#c792ea"' "$panel"
grep -q 'ctx.setLineDash(dashed ? \[5, 4\] : \[\])' "$sparkline"
grep -q 'text: root.heroStatusIcon' "$panel"
! grep -q 'text: "󰖂"' "$panel"
grep -q 'function looksLikeConfig' "$service"
grep -q 'JSON.parse(String(raw || ""))' "$service"
grep -q 'typeof payload.transport !== "string"' "$service"
grep -q 'property var routing:' "$service"
grep -q 'property var coreSetup:' "$service"
grep -q 'property var startup:' "$service"
grep -q 'property bool onboardingComplete:' "$service"
grep -q 'function configureStartup(enabled, target, profileUuid, mode)' "$service"
grep -q 'function completeOnboarding()' "$service"
grep -q 'function loadCustomRules()' "$service"
grep -q 'function addCustomRule(kind, action, value)' "$service"
grep -q 'function checkRoute(value)' "$service"
grep -q 'function refreshRuleProviders()' "$service"
grep -q 'function toggleFavorite(profile)' "$service"
grep -q 'function previewImport(kind, payload, suggestedName)' "$service"
grep -q 'function focusPanelControl(direction)' "$panel"
grep -q 'function handlePanelControlKey(event)' "$panel"
grep -q 'readonly property bool panelTabFocusActive' "$panel"
grep -q 'onTabRequested: function(direction) { root.focusPanelControl(direction) }' "$panel"
! grep -q 'onTabRequested: function(direction) { root.switchPanel(direction) }' "$panel"
grep -q 'advancedDiagnosticsPage.keyboardControlActive' "$panel"
grep -q 'readonly property bool keyboardControlActive' "$advanced_diagnostics"
grep -q 'KeyNavigation.backtab: providersRefreshButton' "$advanced_diagnostics"
grep -q 'KeyNavigation.tab: cancelButton' "$import_preview_prompt"
grep -Fq 'KeyNavigation.tab: prompt.fromFile ? cancelButton : urlField' "$subscription_prompt"
grep -q 'property var filePicker: ({ available: false, provider: "" })' "$service"
grep -q '\["bash", backendPath, "pick-file"\]' "$service"
! grep -q 'root.pickScript' "$service"
grep -q 'File import unavailable — file picker missing' "$service"
grep -q '"gtk4"' "$service"
grep -q 'signal subscriptionImportReady(string kind, string payload, string suggestedName)' "$service"
grep -q 'function exportDiagnostics()' "$service"
grep -q 'function refreshAdvancedDiagnostics()' "$service"
grep -q 'function refreshAdvancedDiagnosticsAfterChange()' "$service"
grep -q 'function applyAdvancedDiagnostics(raw)' "$service"
grep -q 'property bool diagnosticsPageVisible: false' "$service"
grep -q 'id: advancedDiagnosticsProcess' "$service"
grep -q '\["bash", backendPath, "advanced-diagnostics"\]' "$service"
grep -q '_advancedDiagnosticsRequestGeneration !== _advancedDiagnosticsGeneration' "$service"
grep -q 'if (!diagnosticsPageVisible) return false' "$service"
grep -q 'if (advancedDiagnosticsProcess.running)' "$service"
grep -q 'Live Mihomo diagnostics are unavailable' "$service"
diagnostics_visibility_block="$(sed -n \
  '/onDiagnosticsPageVisibleChanged:/,/^  function setting/p' "$service")"
(( $(grep -c 'refreshAdvancedDiagnostics()' <<<"$diagnostics_visibility_block") == 1 ))
diagnostics_refresh_block="$(sed -n \
  '/^  function refreshAdvancedDiagnostics()/,/^  function refreshAdvancedDiagnosticsAfterChange()/p' "$service")"
grep -q 'if (advancedDiagnosticsProcess.running)' <<<"$diagnostics_refresh_block"
grep -q 'return false' <<<"$diagnostics_refresh_block"
(( $(grep -c 'advancedDiagnosticsProcess.running = true' <<<"$diagnostics_refresh_block") == 1 ))
timer_block="$(sed -n '/^  Timer {/,/^  Process {/p' "$service")"
! grep -q 'advancedDiagnostics' <<<"$timer_block"
advanced_process_block="$(sed -n \
  '/id: advancedDiagnosticsProcess/,/id: diagnosticsProcess/p' "$service")"
grep -q 'var stale = !root.diagnosticsPageVisible' <<<"$advanced_process_block"
! grep -q 'lastError' <<<"$advanced_process_block"
grep -Eq '^[[:space:]]*property var capabilities:' "$service"
! grep -q 'readonly property var capabilities:' "$service"
grep -q 'capabilities = featureMap' "$service"
grep -q 'function supports(name)' "$service"
grep -q 'property var conflicts:' "$service"
grep -q 'property string exitIp:' "$service"
grep -q 'property var rxHistory:' "$service"
grep -q 'function plainText(value, maximum)' "$service"
grep -q 'Component.onDestruction:' "$service"
grep -q 'watch-plugin-removal' "$service"
grep -q 'textFormat: Text.PlainText' "$plain_text"
for qml in "$panel" "$service" "$subscription_prompt" "$routing_prompt" \
  "$onboarding_wizard" "$startup_prompt" "$routing_tools_prompt" \
  "$import_preview_prompt" "$advanced_diagnostics" \
  "$here/../NamePrompt.qml" \
  "$here/../RenameWindow.qml" "$here/../QrWindow.qml"; do
  ! grep -Eq '(^|[^A-Za-z])Text \{' "$qml"
done
grep -q 'function drawSeries' "$sparkline"
grep -q 'id: profileSearch' "$panel"
grep -q 'function profileMatches' "$panel"
grep -q '"metric.exit_ip_note"' "$i18n"
grep -q '"warning.full_tunnel_conflict"' "$i18n"
grep -q 'routing.source === "roscomvpn"' "$service"
grep -q 'root.textFor("routing.active")' "$panel"
grep -q 'root.textFor("routing.on_connect")' "$panel"
grep -q 'text: root.routingSummaryText()' "$panel"
grep -q '{ label: root.textFor("mode.routing"), mode: "rule" }' "$panel"
grep -q '{ label: root.textFor("mode.full_vpn"), mode: "global" }' "$panel"
grep -q '{ label: root.textFor("mode.direct"), mode: "direct" }' "$panel"
full_line="$(grep -n '{ label: root.textFor("mode.full_vpn"), mode: "global" }' "$panel" | head -n 1 | cut -d: -f1)"
routing_line="$(grep -n '{ label: root.textFor("mode.routing"), mode: "rule" }' "$panel" | head -n 1 | cut -d: -f1)"
direct_line="$(grep -n '{ label: root.textFor("mode.direct"), mode: "direct" }' "$panel" | head -n 1 | cut -d: -f1)"
(( full_line < routing_line && routing_line < direct_line ))
grep -q 'root.requestRoutingMode(parent.modelData.mode)' "$panel"
grep -q 'function useRoutingPreset(profile, keepMode)' "$service"
grep -q 'RoutingPresetPrompt {' "$panel"
grep -q 'OnboardingWizard {' "$panel"
grep -q 'filePicker: vless.filePicker' "$panel"
grep -q 'title: root.textFor("settings.file_import")' "$panel"
grep -q 'root.textFor("settings.file_picker_missing")' "$panel"
grep -q '"settings.file_picker_missing"' "$i18n"
grep -q 'root.textFor("common.ready") : root.textFor("common.copy_command")' "$panel"
grep -q 'onAction: vless.copyText(root.filePickerInstallCommand)' "$panel"
grep -q 'StartupPrompt {' "$panel"
grep -q 'RoutingToolsPrompt {' "$panel"
grep -q 'ImportPreviewPrompt {' "$panel"
grep -q 'text: "SET UP OMAVLESS"' "$onboarding_wizard"
grep -q 'property var filePicker: ({ available: false, provider: "" })' "$onboarding_wizard"
grep -q 'Clipboard import still works' "$onboarding_wizard"
grep -q 'enabled: wizard.filePicker.available && !wizard.busy' "$onboarding_wizard"
grep -q 'label: "Install a supported file picker"' "$onboarding_wizard"
grep -q 'command: "omarchy pkg add zenity"' "$onboarding_wizard"
grep -q 'text: "START AT LOGIN"' "$startup_prompt"
grep -q 'leftText: "Full VPN"' "$startup_prompt"
grep -q 'rightText: "Routing"' "$startup_prompt"
! grep -q 'Direct' "$startup_prompt"
grep -q 'text: "ROUTING TOOLS"' "$routing_tools_prompt"
grep -q 'text: "Where will this destination go?"' "$routing_tools_prompt"
grep -q 'text: "Custom rules"' "$routing_tools_prompt"
grep -q 'text: "Refresh now"' "$routing_tools_prompt"
grep -q 'no page is loaded' "$routing_tools_prompt"
grep -q 'text: prompt.textFor("import.review")' "$import_preview_prompt"
grep -q '"import.privacy_note"' "$i18n"
grep -q 'credentialHint' "$import_preview_prompt"
grep -q '{ label: prompt.textFor("import.protocol"), value: String(prompt.preview.protocol' "$import_preview_prompt"
grep -q 'compatibilityNote' "$import_preview_prompt"
grep -q 'advancedXhttp' "$import_preview_prompt"
grep -q 'prompt.preview.experimental' "$import_preview_prompt"
grep -q 'onClicked: wizard.copyCommand(commandRow.command)' "$onboarding_wizard"
! grep -q 'runControl' "$onboarding_wizard"
grep -q 'text: "Choose Routing preset"' "$routing_prompt"
grep -q 'Keys.onReturnPressed: if (accepted) confirmed(selectedPreset)' "$routing_prompt"
grep -q 'omarchy bar set ' "$panel"
grep -q 'text: root.textFor("settings.title")' "$panel"
grep -q 'else if (t === "g" || t === "G") root.openSettings()' "$panel"
grep -q 'function setRoutingMode(mode)' "$service"
grep -q 'runControl(\["set-mode", value\])' "$service"
grep -q 'function diagnostics(): string' "$panel"
diagnostics_block="$(sed -n '/function diagnostics(): string {/,/function details(): string/p' "$panel")"
! grep -q 'lastError\|profileId\|subscriptionUrl' <<<"$diagnostics_block"
grep -q 'title: root.textFor("settings.safe_diagnostics")' "$panel"
grep -q 'root.textFor("settings.safe_diagnostics_private")' "$panel"
grep -q '"settings.safe_diagnostics_private"' "$i18n"
grep -q 'function subscriptions()' "$panel"
grep -q 'root.openSubscriptions()' "$panel"
grep -q 'Qt.callLater(root.openSubscriptions)' "$panel"
! grep -q 'function findByIfname' "$service"
! grep -q 'confIfname' "$service"
! grep -q 'findByIfname\|countByIfname\|confIfname' "$panel"
grep -q '(vless|trojan|hysteria2|hy2|tuic):\\/\\/' "$service"
grep -q '"xhttp", "quic"' "$service"
grep -q 'root.capabilities.protocols.indexOf(value.protocol)' "$service"
grep -q 'hysteria2Experimental' "$service"
grep -q 'tuicExperimental' "$service"
grep -Fq '!/^••••(?:[0-9a-f]{4})?$/i.test(value.credentialHint)' "$service"
grep -q 'runControl(\["import", "--"' "$service"
grep -q 'root.previewImport("text", text, root.suggestName())' "$service"
grep -q 'previewProcess.stdinEnabled = sourceKind === "text"' "$service"
grep -q '\["bash", backendPath, "import-preview", "--", sourcePayload\]' "$service"
grep -q '\["bash", backendPath, "import-preview"\]' "$service"
grep -q 'if (result.kind === "subscription")' "$service"
grep -q 'root.subscriptionImportReady(' "$service"
clipboard_block="$(sed -n '/id: clipboardProcess/,/id: previewProcess/p' "$service")"
! grep -q 'looksLikeConfig' <<<"$clipboard_block"
grep -q 'function beginSubscriptionImport(kind, payload, suggested)' "$panel"
grep -q 'function onSubscriptionImportReady(kind, payload, suggestedName)' "$panel"
grep -q 'textFor("subscription.add_from_clipboard")' "$panel"
grep -q '\["bash", backendPath, "export-file", "--", profile.uuid, dest\]' "$service"
grep -Fq 'diagnostics-export -- \"$dest\"' "$service"
grep -q 'diagnostics-export' "$service"
grep -q 'runControl(\["subscription-save", "--"' "$service"
grep -q 'function saveSubscriptionFile(name, uuid, path)' "$service"
grep -q 'runControl(\["subscription-save-file", "--"' "$service"
grep -q 'property string subscriptionImportFile: ""' "$panel"
grep -q 'subscriptionPrompt.openFromFile(name)' "$panel"
grep -q 'vless.saveSubscriptionFile(subscriptionNameClean, uuid, subscriptionImportFile)' "$panel"
grep -q 'property bool fromFile: false' "$subscription_prompt"
grep -q 'function openFromFile(name)' "$subscription_prompt"
grep -q 'text: prompt.textFor("subscription.file_validated")' "$subscription_prompt"
grep -q 'runControl(\["rename", profile.uuid, "--", value\])' "$service"
grep -q '"edit", _editUuid, "--", _editName' "$service"
grep -q '"notify-drop", drop.uuid\]' "$service"
! grep -q '"notify-drop", drop.uuid, drop.name' "$service"
grep -q 'function probeSubscription(subscription)' "$service"
grep -q 'function cancelProbe()' "$service"
grep -q 'property int probeElapsedSeconds: 0' "$service"
grep -q 'property var subscriptionProbeTimes' "$service"
grep -q 'readonly property int managedProfileCount' "$service"
grep -q '"subscription-probe-stream"' "$service"
grep -q 'stdout: SplitParser' "$service"
grep -q 'function applyProbeEvent(raw, expectedSubscriptionUuid)' "$service"
grep -q 'function testActiveConnection()' "$service"
grep -q 'text: root.textFor("action.test")' "$panel"
grep -q 'onClicked: vless.testActiveConnection()' "$panel"
grep -q 'component SubscriptionGroupRow' "$panel"
grep -q 'component SubscriptionServerRow' "$panel"
grep -q 'root.toggleSubscriptionGroup' "$panel"
grep -q 'root.probeLabel' "$panel"
grep -q 'property var subscriptionSortModes' "$panel"
grep -q 'function cycleSubscriptionPingSort' "$panel"
grep -q 'component SubscriptionSortRow' "$panel"
grep -q 'text: sortRow.sortMode === "pingAsc" ? "Ping ↑"' "$panel"
grep -q 'root.textFor("profiles.failed_last")' "$panel"
grep -q 'root.localizedCount("managed_profile", vless.managedProfileCount)' "$panel"
grep -q 'component SubscriptionStatusRow' "$panel"
grep -q 'root.page === "diagnostics"' "$panel"
grep -q 'advancedDiagnosticsPage.implicitHeight' "$panel"
grep -q 'AdvancedDiagnostics {' "$panel"
grep -q 'diagnosticsPageVisible: root.opened && root.page === "diagnostics"' "$panel"
grep -q 'trafficMonitoring: (root.opened && root.page === "main") || vless.showBarThroughput' "$panel"
grep -q 'pingMonitoring: root.opened && root.page === "main"' "$panel"
grep -q 'panelVisible ? refreshIntervalSec : Math.max(30, refreshIntervalSec)' "$service"
grep -q 'text: "LIVE MIHOMO DIAGNOSTICS"' "$advanced_diagnostics"
grep -q 'placeholderText: "Search payload, rule type or VPN / DIRECT / REJECT"' "$advanced_diagnostics"
grep -q 'modelData.target' "$advanced_diagnostics"
grep -q 'service.loadedRuleProviders' "$advanced_diagnostics"
grep -q 'Keys.onEscapePressed: backRequested()' "$advanced_diagnostics"
grep -q 'PlainText {' "$advanced_diagnostics"
! grep -Eq '(^|[^A-Za-z])Text \{' "$advanced_diagnostics"
grep -q 'function probeAge(subscriptionUuid)' "$panel"
grep -q 'function toggleSubscriptionProbe(subscription)' "$panel"
grep -q 'root.textFor("common.cancel") : root.textFor("action.test")' "$panel"
grep -q 'root.toggleSubscriptionProbe(groupRow.subscription)' "$panel"
grep -q '"Run an end-to-end proxy check through every server (p)"' "$panel"
grep -q 'readonly property real scrollGutter: Style.space(16)' "$panel"
grep -q 'if (!pointerSelectingConfig) scrollCursorIntoView()' "$panel"
grep -q 'component SubscriptionServerRow: CursorSurface' "$panel"
grep -q 'vless.toggleFavorite' "$panel"
grep -q 'profile.favorite' "$panel"
grep -q 'bordered: true' "$panel"
grep -q '_dropWarningText' "$service"
grep -q '&& !root.active' "$service"
grep -q 'text: root.textFor("subscriptions.open")' "$panel"
grep -q 'id: subscriptionsButton' "$panel"
(( $(grep -c 'size: subscriptionsButton.implicitHeight' "$panel") == 2 ))
(( $(grep -c 'anchors.verticalCenter: parent.verticalCenter' "$panel") >= 8 ))
grep -q 'function clearKeyboardCursorOnHover(isHovered)' "$panel"
(( $(grep -c 'header.clearKeyboardCursorOnHover(on)' "$panel") == 4 ))
! grep -q 'header.focusHero()' "$panel"
! grep -q 'onHoveredChanged: if (hovered)' "$panel"
grep -q 'URL stays private' "$panel"
grep -q 'echoMode: reveal.checked' "$subscription_prompt"
grep -q 'property bool error: false' "$subscription_prompt"
grep -q 'prompt.textFor("subscription.url_sensitive")' "$subscription_prompt"
grep -q 'controlProcess.stdinEnabled = true' "$service"
grep -q 'URI contains the access credential' "$service"
grep -q 'head -c 65537' "$service"
grep -q 'Clipboard content is too large to import' "$service"
grep -q 'statusPollIntervalMs' "$service"
grep -q 'statusFailureCount = Math.min' "$service"
grep -q '/sys/class/net/\$d/statistics' "$service"
grep -q 'rx - prev.rx' "$service"
grep -q 'tx - prev.tx' "$service"
! grep -q '/traffic' "$service"
! grep -q 'vless-last' "$service"
grep -q 'moduleName: "kdk.omavless"' "$panel"
grep -q 'fresh_install=false' "$installer"
grep -q 'local-plugin watcher debounces' "$installer"
grep -q '"$plugin_dir/uninstall.sh"' "$installer"
grep -q '"$plugin_dir/SubscriptionPrompt.qml"' "$installer"
grep -q '"$plugin_dir/RoutingPresetPrompt.qml"' "$installer"
grep -q '"$plugin_dir/OnboardingWizard.qml"' "$installer"
grep -q '"$plugin_dir/StartupPrompt.qml"' "$installer"
grep -q '"$plugin_dir/RoutingToolsPrompt.qml"' "$installer"
grep -q '"$plugin_dir/ImportPreviewPrompt.qml"' "$installer"
grep -q '"$plugin_dir/PlainText.qml"' "$installer"
grep -q '"$plugin_dir/AdvancedDiagnostics.qml"' "$installer"
grep -q '"$plugin_dir/I18n.js"' "$installer"
grep -q '"$plugin_dir/Sparkline.qml"' "$installer"
grep -q '"$plugin_dir/CHANGELOG.md"' "$installer"
grep -q 'omarchy pkg add zenity' "$installer"
grep -q 'Clipboard import remains available' "$installer"
grep -q 'FileChooserNative' "$installer"
! grep -Eq 'sudo.*zenity|pkexec.*zenity' "$installer"
! grep -q 'omarchy plugin disable' "$installer"
! grep -q 'omarchy restart shell' "$installer"
grep -q 'import "I18n.js" as I18n' "$panel"
grep -q 'import "I18n.js" as I18n' "$subscription_prompt"
grep -q 'import "I18n.js" as I18n' "$import_preview_prompt"
grep -q 'Quickshell.env("OMAVLESS_LOCALE")' "$panel"
grep -q 'Qt.locale().name' "$panel"
grep -q 'function normalizeLocaleSetting(value)' "$panel"
grep -q 'id: settingsLanguageRow' "$panel"
grep -q 'root.setWidgetSetting("locale", next, false)' "$panel"
language_cycle_block="$(sed -n '/^  function cycleLanguageSetting()/,/^  }/p' "$panel")"
! grep -Eq 'vless\.|backend|restart|disconnect|connect' <<<"$language_cycle_block"
grep -q 'function normalizeLocale(value)' "$i18n"
grep -q 'function translate(key, locale, values)' "$i18n"
grep -q 'Missing translation:' "$i18n"
grep -q 'MAX_TEXT_LENGTH = 512' "$i18n"
grep -q 'MAX_VALUE_LENGTH = 160' "$i18n"
grep -q '"error.manual_recovery_required"' "$i18n"
grep -q '"settings.language_description"' "$i18n"
grep -q 'text: root.textFor("profiles.no_match"' "$panel"
grep -q 'text: prompt.textFor("import.privacy_note")' "$import_preview_prompt"
grep -q 'locale: root.uiLocale' "$panel"
bash -n "$installer"
bash -n "$uninstaller"

if command -v qmllint >/dev/null 2>&1; then
  qmllint "$panel"
  qmllint "$service"
  qmllint "$subscription_prompt"
  qmllint "$routing_prompt"
  qmllint "$onboarding_wizard"
  qmllint "$startup_prompt"
  qmllint "$routing_tools_prompt"
  qmllint "$import_preview_prompt"
  qmllint "$advanced_diagnostics"
  qmllint "$plain_text"
  qmllint "$sparkline"
fi

echo "QML contracts: ok"
