// SPDX-License-Identifier: MIT

//! Pure subscription refresh planning. Remote fetch and disk commit remain
//! outside this module so callers can validate the complete plan before one
//! atomic private-store replacement.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

pub const MAX_PROFILE_COUNT: usize = 256;
pub const MAX_PROFILE_NAME_CHARS: usize = 80;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SyncError {
    TooManyEntries,
    DuplicateEntry,
    AmbiguousExistingIdentity,
    DuplicateGeneratedId,
    TooManyProfiles,
    NameExhausted,
}

impl SyncError {
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::TooManyEntries => "too_many_subscription_entries",
            Self::DuplicateEntry => "duplicate_subscription_entry",
            Self::AmbiguousExistingIdentity => "ambiguous_subscription_identity",
            Self::DuplicateGeneratedId => "duplicate_generated_profile_id",
            Self::TooManyProfiles => "too_many_profiles",
            Self::NameExhausted => "profile_name_exhausted",
        }
    }
}

impl fmt::Display for SyncError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::TooManyEntries => "Subscription contains too many profiles",
            Self::DuplicateEntry => "Subscription contains a duplicate profile",
            Self::AmbiguousExistingIdentity => "Subscription identity is ambiguous",
            Self::DuplicateGeneratedId => "Generated profile record ID is duplicated",
            Self::TooManyProfiles => "Subscription would exceed the profile limit",
            Self::NameExhausted => "Could not create a unique profile name",
        })
    }
}

impl std::error::Error for SyncError {}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManagedProfile {
    pub id: String,
    pub name: String,
    pub subscription_id: String,
    pub subscription_key: String,
    /// Recomputed canonical identity from the stored URI, when available.
    pub derived_key: String,
    pub missing: bool,
    pub favorite: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IncomingProfile {
    pub key: String,
    pub desired_name: String,
    /// Pre-generated by the caller; ignored when an existing record matches.
    pub new_id: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SyncCounts {
    pub added: usize,
    pub removed: usize,
    pub stale: usize,
    pub total: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SyncPlan {
    pub profiles: Vec<ManagedProfile>,
    pub last_id: String,
    pub counts: SyncCounts,
}

fn clean_provider_name(value: &str) -> String {
    value
        .chars()
        .filter(|character| !matches!(*character as u32, 0x00..=0x1f | 0x7f))
        .collect::<String>()
        .trim()
        .chars()
        .take(MAX_PROFILE_NAME_CHARS)
        .collect()
}

fn prefix_chars(value: &str, count: usize) -> String {
    value.chars().take(count).collect()
}

fn unique_name(
    desired: &str,
    subscription_name: &str,
    used: &mut BTreeSet<String>,
) -> Result<String, SyncError> {
    let mut base = clean_provider_name(desired);
    if base.is_empty() {
        base = "Profile".to_owned();
    }
    let source: String = subscription_name.chars().take(76).collect();
    let source_suffix = format!(" · {source}");
    let source_room = MAX_PROFILE_NAME_CHARS.saturating_sub(source_suffix.chars().count());
    let choices = [
        base.clone(),
        format!(
            "{}{}",
            prefix_chars(&base, source_room.max(1)),
            source_suffix
        ),
    ];
    for choice in choices {
        if used.insert(choice.clone()) {
            return Ok(choice);
        }
    }
    for number in 2..=MAX_PROFILE_COUNT + 1 {
        let suffix = format!(" · {number}");
        let room = MAX_PROFILE_NAME_CHARS.saturating_sub(suffix.chars().count());
        let candidate = format!("{}{}", prefix_chars(&base, room.max(1)), suffix);
        if used.insert(candidate.clone()) {
            return Ok(candidate);
        }
    }
    Err(SyncError::NameExhausted)
}

pub fn plan_subscription_sync(
    profiles: &[ManagedProfile],
    subscription_id: &str,
    subscription_name: &str,
    entries: &[IncomingProfile],
    active_id: &str,
    last_id: &str,
) -> Result<SyncPlan, SyncError> {
    let mut entry_keys = BTreeSet::new();
    if entries.iter().any(|entry| !entry_keys.insert(&entry.key)) {
        return Err(SyncError::DuplicateEntry);
    }
    let existing_profiles: Vec<_> = profiles
        .iter()
        .filter(|profile| profile.subscription_id == subscription_id)
        .collect();
    let mut existing = BTreeMap::<&str, &ManagedProfile>::new();
    let mut ambiguous = BTreeSet::new();
    for profile in &existing_profiles {
        for key in [&profile.subscription_key, &profile.derived_key] {
            if key.is_empty() {
                continue;
            }
            if existing
                .insert(key, profile)
                .is_some_and(|previous| previous.id != profile.id)
            {
                ambiguous.insert(key.as_str());
            }
        }
    }
    let mut used_names: BTreeSet<String> = profiles
        .iter()
        .filter(|profile| profile.subscription_id != subscription_id)
        .map(|profile| profile.name.clone())
        .collect();
    let mut used_ids: BTreeSet<String> =
        profiles.iter().map(|profile| profile.id.clone()).collect();
    let mut matched = BTreeSet::new();
    let mut synced = Vec::with_capacity(entries.len());
    let mut added = 0;
    for entry in entries {
        if ambiguous.contains(entry.key.as_str()) {
            return Err(SyncError::AmbiguousExistingIdentity);
        }
        let name = unique_name(&entry.desired_name, subscription_name, &mut used_names)?;
        let profile = if let Some(current) = existing.get(entry.key.as_str()) {
            if !matched.insert(current.id.as_str()) {
                return Err(SyncError::AmbiguousExistingIdentity);
            }
            ManagedProfile {
                id: current.id.clone(),
                name,
                subscription_id: subscription_id.to_owned(),
                subscription_key: entry.key.clone(),
                derived_key: entry.key.clone(),
                missing: false,
                favorite: current.favorite,
            }
        } else {
            if !used_ids.insert(entry.new_id.clone()) {
                return Err(SyncError::DuplicateGeneratedId);
            }
            added += 1;
            ManagedProfile {
                id: entry.new_id.clone(),
                name,
                subscription_id: subscription_id.to_owned(),
                subscription_key: entry.key.clone(),
                derived_key: entry.key.clone(),
                missing: false,
                favorite: false,
            }
        };
        synced.push(profile);
    }
    let mut removed = BTreeSet::new();
    let mut stale = 0;
    for profile in existing_profiles {
        if matched.contains(profile.id.as_str()) {
            continue;
        }
        if profile.id == active_id {
            let mut retained = profile.clone();
            retained.missing = true;
            synced.push(retained);
            stale += 1;
        } else {
            removed.insert(profile.id.as_str());
        }
    }
    let mut result: Vec<_> = profiles
        .iter()
        .filter(|profile| profile.subscription_id != subscription_id)
        .cloned()
        .collect();
    result.extend(synced);
    if result.len() > MAX_PROFILE_COUNT {
        return Err(SyncError::TooManyProfiles);
    }
    let next_last = if removed.contains(last_id) {
        result
            .first()
            .map_or_else(String::new, |profile| profile.id.clone())
    } else {
        last_id.to_owned()
    };
    Ok(SyncPlan {
        profiles: result,
        last_id: next_last,
        counts: SyncCounts {
            added,
            removed: removed.len(),
            stale,
            total: entries.len(),
        },
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn profile(id: &str, key: &str, favorite: bool) -> ManagedProfile {
        ManagedProfile {
            id: id.into(),
            name: "Old".into(),
            subscription_id: "sub".into(),
            subscription_key: key.into(),
            derived_key: key.into(),
            missing: false,
            favorite,
        }
    }

    #[test]
    fn refresh_preserves_id_favorite_and_marks_only_active_missing() {
        let profiles = [
            profile("one", "key-one", true),
            profile("two", "key-two", false),
        ];
        let entries = [IncomingProfile {
            key: "key-one".into(),
            desired_name: "New".into(),
            new_id: "unused".into(),
        }];
        let plan =
            plan_subscription_sync(&profiles, "sub", "Source", &entries, "two", "two").unwrap();
        assert_eq!(
            plan.counts,
            SyncCounts {
                added: 0,
                removed: 0,
                stale: 1,
                total: 1
            }
        );
        assert_eq!(plan.profiles[0].id, "one");
        assert!(plan.profiles[0].favorite);
        assert!(plan.profiles[1].missing);
    }

    #[test]
    fn inactive_removed_profile_repairs_last_pointer() {
        let profiles = [profile("one", "old", false)];
        let plan = plan_subscription_sync(&profiles, "sub", "Source", &[], "", "one").unwrap();
        assert_eq!(plan.counts.removed, 1);
        assert!(plan.profiles.is_empty());
        assert_eq!(plan.last_id, "");
    }

    #[test]
    fn derived_identity_migrates_key_and_duplicate_inputs_fail() {
        let mut old = profile("one", "legacy", true);
        old.derived_key = "canonical".into();
        let entries = [IncomingProfile {
            key: "canonical".into(),
            desired_name: "Node".into(),
            new_id: "new".into(),
        }];
        assert_eq!(
            plan_subscription_sync(&[old], "sub", "S", &entries, "", "")
                .unwrap()
                .counts
                .added,
            0
        );
        assert_eq!(
            plan_subscription_sync(
                &[],
                "sub",
                "S",
                &[entries[0].clone(), entries[0].clone()],
                "",
                ""
            )
            .unwrap_err(),
            SyncError::DuplicateEntry
        );
    }

    #[test]
    fn one_existing_profile_cannot_satisfy_two_incoming_identities() {
        let mut old = profile("one", "provider-key", true);
        old.derived_key = "canonical-key".into();
        let entries = [
            IncomingProfile {
                key: "provider-key".into(),
                desired_name: "First".into(),
                new_id: "unused-one".into(),
            },
            IncomingProfile {
                key: "canonical-key".into(),
                desired_name: "Second".into(),
                new_id: "unused-two".into(),
            },
        ];
        assert_eq!(
            plan_subscription_sync(&[old], "sub", "S", &entries, "", "").unwrap_err(),
            SyncError::AmbiguousExistingIdentity
        );
    }

    #[test]
    fn provider_names_are_bounded_and_deduplicated() {
        let other = ManagedProfile {
            id: "other".into(),
            name: "Profile".into(),
            subscription_id: "else".into(),
            subscription_key: "".into(),
            derived_key: "".into(),
            missing: false,
            favorite: false,
        };
        let entries = [IncomingProfile {
            key: "k".into(),
            desired_name: "\0\n".into(),
            new_id: "new".into(),
        }];
        let plan =
            plan_subscription_sync(&[other], "sub", &"S".repeat(100), &entries, "", "").unwrap();
        assert!(plan.profiles[1].name.chars().count() <= 80);
        assert_ne!(plan.profiles[1].name, "Profile");
    }
}
